name: Publish

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: costateixeira/mynewig 
        ref: refs/heads/main
