name: Publish

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        name: costateixeira/mynewig     <-- clone https://github.com/org1/repo1
        ref: refs/heads/main
